In [20]:
!pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (2.5.1)
Requirement already satisfied: matplotlib in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (3.11.1)
Requirement already satisfied: seaborn in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/sergio/Projects/Energy-Efficiency/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
db_url = 'https://raw.githubusercontent.com/deepakorani/Energy-Efficiency/master/ENB2012_data.csv'

# carregando os dados do csv na var df. 
# Optei por nao colocar baixar os dados e carregá-los pelo caminho relativo pois fazendo assim 
# da para usar algo como o google colab
df = pd.read_csv(db_url)

In [23]:
# Podemos visualizar as primeiras linhas do DF com o metodo head()
display(df.head())

,X1,X2,X3,X4,X5,X6,X7,X8,Y1,Y2,Unnamed: 10,Unnamed: 11
0,0.98,514.5,294.0,110.25,7.0,2.0,0.0,0.0,15.55,21.33,NaN,NaN
1,0.98,514.5,294.0,110.25,7.0,3.0,0.0,0.0,15.55,21.33,NaN,NaN
2,0.98,514.5,294.0,110.25,7.0,4.0,0.0,0.0,15.55,21.33,NaN,NaN
3,0.98,514.5,294.0,110.25,7.0,5.0,0.0,0.0,15.55,21.33,NaN,NaN
4,0.90,563.5,318.5,122.50,7.0,2.0,0.0,0.0,20.84,28.28,NaN,NaN

Podemos prosseguir sem atribuir numeros as colunas, pois isso é somente uma interpretação semântica humana. No entanto, para legibilidade, podemos renomear as colunas para podermos visualizar melhor os dados

Alem disso, veja que temos as colunas "Unnamed: 10" e "Unnamed: 11" que parecem conter apenas valores do tipo NaN. Podemos verificar isso

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   X1           768 non-null    float64
 1   X2           768 non-null    float64
 2   X3           768 non-null    float64
 3   X4           768 non-null    float64
 4   X5           768 non-null    float64
 5   X6           768 non-null    float64
 6   X7           768 non-null    float64
 7   X8           768 non-null    float64
 8   Y1           768 non-null    float64
 9   Y2           768 non-null    float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
dtypes: float64(12)
memory usage: 121.6 KB

Então, podemos remover essas colunas, ou só selecionar as primeiras 10 colunas.

In [25]:
# Removendo as colunas inuteis
df = df.iloc[:, 0:10]

In [26]:
# testando
df.info()
display(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X1      768 non-null    float64
 1   X2      768 non-null    float64
 2   X3      768 non-null    float64
 3   X4      768 non-null    float64
 4   X5      768 non-null    float64
 5   X6      768 non-null    float64
 6   X7      768 non-null    float64
 7   X8      768 non-null    float64
 8   Y1      768 non-null    float64
 9   Y2      768 non-null    float64
dtypes: float64(10)
memory usage: 101.4 KB

     X1     X2     X3      X4   X5   X6   X7   X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0  2.0  0.0  0.0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0  3.0  0.0  0.0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0  4.0  0.0  0.0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0  5.0  0.0  0.0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0  2.0  0.0  0.0  20.84  28.28

In [27]:
# Renomeando as colunas

colunas = {
    'X1': 'compacidade_relativa',
    'X2': 'area_superficie',
    'X3': 'area_parede',
    'X4': 'area_telhado',
    'X5': 'altura_total',
    'X6': 'orientacao',
    'X7': 'area_envidracada',
    'X8': 'distrib_area_envidracada',
    'Y1': 'carga_aquecimento', # Target 1
    'Y2': 'carga_resfriamento' # Target 2
}
df = df.rename(columns=colunas)

In [28]:
display(df.head())

,compacidade_relativa,area_superficie,area_parede,area_telhado,altura_total,orientacao,area_envidracada,distrib_area_envidracada,carga_aquecimento,carga_resfriamento
0,0.98,514.5,294.0,110.25,7.0,2.0,0.0,0.0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3.0,0.0,0.0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4.0,0.0,0.0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5.0,0.0,0.0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2.0,0.0,0.0,20.84,28.28

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   compacidade_relativa      768 non-null    float64
 1   area_superficie           768 non-null    float64
 2   area_parede               768 non-null    float64
 3   area_telhado              768 non-null    float64
 4   altura_total              768 non-null    float64
 5   orientacao                768 non-null    float64
 6   area_envidracada          768 non-null    float64
 7   distrib_area_envidracada  768 non-null    float64
 8   carga_aquecimento         768 non-null    float64
 9   carga_resfriamento        768 non-null    float64
dtypes: float64(10)
memory usage: 101.4 KB

In [30]:
# Vamos fazer a regressão no Y1 primeiro, pra isso, podemos remover o Y2. 

df = df.drop(columns=['carga_resfriamento'])

print("Dimensões do dataset:", df.shape)
display(df.head())

Dimensões do dataset: (1296, 9)

,compacidade_relativa,area_superficie,area_parede,area_telhado,altura_total,orientacao,area_envidracada,distrib_area_envidracada,carga_aquecimento
0,0.98,514.5,294.0,110.25,7.0,2.0,0.0,0.0,15.55
1,0.98,514.5,294.0,110.25,7.0,3.0,0.0,0.0,15.55
2,0.98,514.5,294.0,110.25,7.0,4.0,0.0,0.0,15.55
3,0.98,514.5,294.0,110.25,7.0,5.0,0.0,0.0,15.55
4,0.90,563.5,318.5,122.50,7.0,2.0,0.0,0.0,20.84